// Central export for all services
export { default as authService } from '@/features/auth/services/authService'
export { bookingService } from '@/features/booking'
export { default as paymentService } from './paymentService'
export { default as fleetService } from './fleetService'
export { default as driverService } from './driverService'
export { default as tripService } from './tripService'
export { default as clientService } from './clientService'
export { default as reconciliationService } from './reconciliationService'
export { default as reportService } from './reportService'
export { default as temperatureService } from './temperatureService'
export { default as addressService } from './addressService'
export { dashboardService } from '@/features/dashboard'
export { default as notificationService } from './notificationService'
export { default as uploadService } from './uploadService'
export { default as validationService } from './validationService'
export { default as pdfService } from './pdfService'
export { default as securityService } from './securityService'
export { default as adminService } from './adminService'
export { default as httpClient } from './httpClient'
